default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#local
#development:
#  <<: *default
#  database: app_desarrollo
#  pool: 5
#  username: davidmao
#  password: cataratas
#  host: localhost

development:
  <<: *default
  database: d1j9ll43fnq5m
  pool: 5
  username: amxjhpojzefhzk
  password: 60619814fc253a3fee1fd445f818810b779f57193b21e4d1221b1037ed5f0860
  host:     ec2-54-163-255-181.compute-1.amazonaws.com
  sslmode:  require

test:
  <<: *default
  database: app_test


production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
